### ISSUE TITLE
when tap fast, the slider block did not slide

### ISSUE THREAD

**Issue by guopeng1994** [App2Sales/react-native-switch-selector#1]
The TouchableOpacity component feedback the opacity style while tapping, but the block did not slide, sometimesi have to tap a lot of times to make it move.

**Comment by jkdrangel** [comment]
Thank you for reporting your issue. This error normally happens in debug with remote debug enabled. Try disabling it and test again. 
The remote debug sometimes delays the animations causing this error. 
If the error persists please comment here again.
