### ISSUE TITLE
How to disable the switch selector functionality?

### ISSUE THREAD

**Issue by akhileshsinha** [App2Sales/react-native-switch-selector#10]
In some circumstances, I need to disable the selection functionality. Please add a prop for disabling it.

**Comment by naveedshahji** [comment]
@akhileshsinha have you find any solution for it

**Comment by akhileshsinha06** [comment]
@naveedshahji I didn't find any solution but I did a workaround. I used a transparent view to cover that component whenever I needed that component to be disabled. I know it's not a great option but it solved my issue.

**Comment by is343** [comment]
I made a PR #27 to add a disable prop

**Comment by naveedshahji** [comment]
I tried with disabled = 'true' but not working for me.

**Comment by is343** [comment]
@naveedshahji 
Try it with
`disabled={true}`
