### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [App2Sales/react-native-switch-selector#11]
@App2Sales, @jkdrangel : 
Hello, congratulations for the module.
I did this: https://snack.expo.io/ryhqT6aJm
I have to do something like this:

![screenshot_20180531-212937](https://user-images.githubusercontent.com/20476002/40804008-680d2560-651a-11e8-91af-8a0c1d7429ac.jpeg)

1) How do I reduce the height of the switch-selector?
2) To put a bold effect on the text of the switch-selector?

**Comment by Angelk90** [comment]
@jkdrangel : I made some changes, here you find the modified react-native-switch-selector file: https://snack.expo.io/HJhKQmAJX
- onPress returns the selected status, not just the value
- added bold
- added height
- added valuePadding

There is the valuePadding to be fixed, considering the height set.
this value should have only two values 1 or 2, higher values would lose significance.
in case only if hasPadding == true.

A nice idea would do such a thing: https://cdn-images-1.medium.com/max/800/1*fFIPdEtcEbDlR8akHCDbOg.jpeg
In place of the tab use this component to be able to change the tabs, simply with the slider.
https://hackernoon.com/how-to-use-a-custom-header-and-custom-bottom-tab-bar-for-react-native-with-react-navigation-969a5d3cabb1

**Comment by jkdrangel** [comment]
@Angelk90 thanks for your contributions. I added a new prop returnObject to keep consistence with old versions.
[1.1.7](https://github.com/App2Sales/react-native-switch-selector/releases/tag/1.1.7)

**Comment by Angelk90** [comment]
@jkdrangel : What do you think of the idea of creating a tab-slider?

**Comment by jkdrangel** [comment]
@Angelk90, I can not think now. This component was created for a project and I'm only maintenance it now because of other demand, but i think that with few changes this component can turn a tab-slider.

**Comment by Angelk90** [comment]
@jkdrangel : I asked you why the code is yours.
I was trying to think how to do it, more or less I'm almost successful, except for the fact that when I'm on the page and I have to make the slider to the right or left I still do not know how to change the page.
It was because I did not want to take advantage of the code you wrote.
In the event that I posted it on github.

**Comment by jkdrangel** [comment]
@Angelk90, I do not see problem in that this code is availed in another project. You can take advantage of what you have here and reference it. Maybe I can contribute in your tab-slider later too.

I did something similar with a custom tab using conditional rendering, you can try this to solve the problem.

**Comment by jkdrangel** [comment]
OnPress has changed a state in the parent component that has a conditional rendering based on that state.

**Comment by Angelk90** [comment]
@jkdrangel : I thought about using the ScrollView?
But I'm not understanding why it does not work.
Link: https://snack.expo.io/ByWUw2C17
If you can take a look. ;)

**Comment by Angelk90** [comment]
@jkdrangel :  The problem is that on the page if I wanted to make a slide on the page to the right or left, I would like to change the page.

**Comment by jkdrangel** [comment]
In this case the panResponder code in the switch selector should be present in the screen too, and force the update of the selected value in selector.

**Comment by jkdrangel** [comment]
You can change the increments in the responderEnd. 
As for the transition, maybe the [layoutAnimation](https://facebook.github.io/react-native/docs/layoutanimation.html#docsNav) will help.

**Comment by Angelk90** [comment]
@jkdrangel : 
I did it this way it works, change to:
sx con dx the other way around
```
_getSwipeDirection(gestureState) {
    const { dx, dy, vx } = gestureState;
    // 0.1 velocity
    if (Math.abs(vx) > 0.1 && Math.abs(dy) < 80) {
      return dx > 0 ? 'LEFT' : 'RIGHT';
    }
    return null;
  }
```
But do you think it's logically wrong?

P.s.
You could give me a hand with this animation thing, I'm not very competent in this field, I do not know if I could.
