### ISSUE TITLE
skewed button

### ISSUE THREAD

**Issue by hungdev** [App2Sales/react-native-switch-selector#13]
The button seems to be upside down.
and could you tell me how to get border without padding?
thank you.
<img width="1220" alt="screen shot 2018-06-04 at 10 21 31 pm" src="https://user-images.githubusercontent.com/12009276/40926207-e47165ca-6845-11e8-8555-d80b5916e6f6.png">
<img width="483" alt="screen shot 2018-06-04 at 10 24 50 pm" src="https://user-images.githubusercontent.com/12009276/40926314-21080cdc-6846-11e8-986e-e641a4c57527.png">

**Comment by jkdrangel** [comment]
@hungdev Thanks for this issue. Try the new [1.1.8](https://github.com/App2Sales/react-native-switch-selector/releases/tag/1.1.8) version.
