### ISSUE TITLE
Slider Unresponsive on Device

### ISSUE THREAD

**Issue by nikohosn** [App2Sales/react-native-switch-selector#2]
Hi there,

Tested on Android and iOS.. When tapping the slider to 'toggle' the options, it works as expected on simulator with the animation sliding over to the 'tapped' option. 

But when testing on device.. the toggle is unresponsive and it doesn't slide over. Any ideas on what is causing this?
  
Example options:

`const currencyOptions = [
      { label: 'USD', value: 'USD' },
      { label: 'AUD', value: 'AUD' },
      { label: 'CAD', value: 'CAD' },
    ];`

Example use of the component:
`<SwitchSelector 
                         buttonColor='#404F5B' 
                         options={currencyOptions} initial={0} 
                         onPress={value => this.selectItemToBuyToggle(value)}/>`
  
  What's weird is that it works flawlessly on the iOS sim.. Any help would be appreciated

**Comment by nikohosn** [comment]
`            <View style={[{marginTop: 15, marginHorizontal: 50 }]}>
                  <View style={[{ justifyContent: 'center', alignItems: 'center' }]}>
                    <SwitchSelector buttonColor='#404F5B' options={currencyOptions} initial={0} onPress={value => this.selectCoinToBuyToggle(value)}/>
                  </View>
                </View>`

**Comment by jkdrangel** [comment]
Thank you for reporting your issue. This error normally happens in debug with remote debug enabled. Try disabling it and test again.
The remote debug sometimes delays the animations causing this error.
If the error persists please comment here again.
[1](https://github.com/App2Sales/react-native-switch-selector/issues/1)

**Comment by nikohosn** [comment]
Can you elaborate on this line:

 "This error normally happens in debug with remote debug enabled. Try disabling it and test again."

I am running this on device in release mode on android and the same for iOS. The app is being deployed via buddybuild.

**Comment by jkdrangel** [comment]
I updated the component, try the new version 1.0.10.

**Comment by nikohosn** [comment]
Looks great! Thanks for the fix. What was the issue if you don't mind me asking?

**Comment by jkdrangel** [comment]
Some issue in hitslop.
