### ISSUE TITLE
Adjust Button Styling?

### ISSUE THREAD

**Issue by Zukye** [App2Sales/react-native-switch-selector#20]
Hi there, 
I created a toggle which looks a bit odd in one of the states. 
When state is 0, it looks just fine, but in state 1 the margin to the border is not kept. 
![grafik](https://user-images.githubusercontent.com/11507313/43083219-4c53c842-8e96-11e8-9cf0-6e42b229dff5.png)

This is my code: 
```
      <Container style={{height: 40, maxWidth: 120}}>
        <SwitchSelector
          initial={index}
          onPress={value => this.onToggle(value)}
          backgroundColor={"transparent"}
          textColor={colors.white}
          selectedColor={colors.secondary3}
          buttonColor={colors.secondary1}
          borderColor={colors.secondary1}
          hasPadding
          valuePadding={1}
          options={[
            {value: false, customIcon: iconUnlocked},
            {value: true, customIcon: iconLocked}
          ]}/>
      </Container>
```
The issue also appears whitout the container component around it. Any ideas how to fix this or how this is caused?

**Comment by Just01** [comment]
Have same issue. Any solutions?

**Comment by jkdrangel** [comment]
https://github.com/App2Sales/react-native-switch-selector/releases/tag/1.1.12
