### ISSUE TITLE
Using another function to trigger switch

### ISSUE THREAD

**Issue by aliy321** [App2Sales/react-native-switch-selector#21]
Switch status changes but the switch doesnt move. Is there a way to make it move?

**Comment by ChronSyn** [comment]
On your switch component, assign a `ref` prop as so;
`ref={ref => this.dateSelectorSwitch = ref}`

Then simply call the following (changing 0 for the index of the item to switch to);
`this.dateSelectorSwitch.toggleItem(0);`

**Comment by jkdrangel** [comment]
@ChronSyn Thanks for this reply

**Comment by aliy321** [comment]
im getting toggleItem of undefined. 

Using "react-native-switch-selector": "^1.1.8"

**Comment by aliy321** [comment]
Hi, i still cant get this to work, is there any other suggestions? on release build i get this error.

This error is log from xcode - e.props.showAlert is not a function

if i remove the line of code of ref = {...}, i wont get that error

**Comment by naveedshahji** [comment]
@aliy321 have you solved this issue, i am facing same issue.

**Comment by naveedshahji** [comment]
I solved by changing initial={this.state.opt} on trigger change the value of the "opt"

**Comment by fadiaIW** [comment]
For those using hooks, this worked for me. 

const switchRef = useRef(null);

//create a ref 
ref={switchRef};

//Call the following (change 0 for the index of the other item)
switchRef.current.toggleItem(0);
