### ISSUE TITLE
text string must be rendered within a text component

### ISSUE THREAD

**Issue by gunduzcihat** [App2Sales/react-native-switch-selector#32]
My code doesn't work. 
Here is the code: 

`<View style={styles.generalViewPart}>
                <Text style={styles.stepText}>ADIM 1 / 3</Text>
                <Text style={styles.topTitle}>Lorem ipsum</Text>
                <Text style={styles.topText}>Lorem ipsumLorem ipsum</Text>
                <View style={styles.promoTextView}>
                <Text style={styles.promoText}>Lorem ipsumLorem ipsumLorem ipsum</Text>
                </View>

                <SwitchSelector
                  initial={0}
                  onPress={value => console.warn('deneme')} //this.setState({ gender: value })
                  textColor={'#7a44cf'} //'#7a44cf'
                  selectedColor={'red'}
                  buttonColor={'blue'}
                  borderColor={'black'}
                  hasPadding
                  options={[
                    { label: "Feminino", value: "f", imageIcon: '' }, 
                    { label: "Masculino", value: "m", imageIcon: '' } 
                  ]}
                />
</View>`

**Comment by sinansonmez** [comment]
Please try to explain in more detail what is not working in your code?

**Comment by tyson90** [comment]
If you don't need to use imageIcon, remove this key from options.
I just tested it and its works after removing empty imageIcon strings.

**Comment by ssscassio** [comment]
@tyson90 's reply solves this issue. 
https://codesandbox.io/s/react-native-cfymp
May close it @jkdrangel
