### ISSUE TITLE
Warning: componentWillReceiveProps is deprecated in 0.60 

### ISSUE THREAD

**Issue by harshdvaid24** [App2Sales/react-native-switch-selector#42]
Hi there, I am using this component, It's Cool. 
Working fine with all the React-native version in Android/ IOS.
but since last React-native update 0.60 It shows Warning of componentWillReceiveProps is deprecated in 0.60.

Please take a look.
-Thanks

**Comment by rpCal** [comment]
There is pull request to update that

**Comment by ssscassio** [comment]
#44 Solve it
Should close it @jkdrangel  👍
