### ISSUE TITLE
Previous value on componentDidUpdate()

### ISSUE THREAD

**Issue by patlux** [App2Sales/react-native-switch-selector#54]
Hi

https://github.com/App2Sales/react-native-switch-selector/blob/664029cdf80e9347a0e2bf83d0d3f2cc999e3aca/index.js#L51

Is there any reason to set the previous value again in `componentDidUpdate(prevProps)`?

I'm using the component in a controlled way:

```jsx
<SwitchSelector
          value={selectedOptionIndex}
          onPress={onToggleOption}
          options={options}
/>
```

But it doesn't work: It will always end in a endless loop, because it's set the previous value each time.

It's only working when I change the line to:

```js
this.toggleItem(this.props.value, !this.props.disableValueChangeOnPress);
```

Best regards,
patlux

**Comment by abury** [comment]
Came here to fix this exact issue, gw.
