### ISSUE TITLE
No spacing at the top on the button

### ISSUE THREAD

**Issue by dragma** [App2Sales/react-native-switch-selector#56]
Hello
firt of all, thank you for this module. It looks great, and smooth.
I'm trying to implement this in my app, but the buttons style seems wrong. The margin at the top is always 0, then the selector looks like this :
![Screenshot_20200121-155106](https://user-images.githubusercontent.com/4975026/72814919-272fdb80-3c66-11ea-9a66-f05a850c81bf.jpg)
Do you know why ?
:)

My code:

```javascript

        <SwitchSelector
          initial={1}
          value={appMode}
          options={options}
          onPress={onchangeAppMode}
          height={35}
          hasPadding
          buttonMargin={0}
        />

```

**Comment by tzwickl** [comment]
Same here would be nice if we could solve this somehow :) 
Otherwise, this toggle button is really awesome :)

<img width="301" alt="Screenshot 2020-01-24 at 20 36 45" src="https://user-images.githubusercontent.com/4968212/73098264-51450000-3ee9-11ea-92b4-3753a06e6e86.png">

**Comment by ssscassio** [comment]
@jkdrangel I am not sure, but I think that this line is causing the issue.

https://github.com/App2Sales/react-native-switch-selector/blob/3a5e3297bbd017f180df1e10daa8a922fc7726b4/index.js#L216

I can't test it right now, but maybe align the AnimatedView to center and change this constant `4` to `paddingValue * 2` may fix the issue.

If align AnimatedView to center is not possible, maybe add a `marginTop` style with the `paddingValue` may fix it also.

**Comment by jkdrangel** [comment]
Thanks @ssscassio. @dragma @tzwickl try the new version. [2.0.3](https://github.com/App2Sales/react-native-switch-selector/releases/tag/v2.0.3)

**Comment by tzwickl** [comment]
@jkdrangel thanks for the quick fix works :)
