### ISSUE TITLE
Swipe gesture does not work

### ISSUE THREAD

**Issue by vjoao** [App2Sales/react-native-switch-selector#6]
Checking my users' actions, many of them try to swipe to change instead of tapping.
Can this be done as an improvement?

Thanks in advance

**Comment by luisbajana** [comment]
Yep, just got that feedback from my users too. I'll try to find a workaround.

**Comment by jkdrangel** [comment]
Thanks for yours sugestions. Please, try the new version [1.1.4](https://github.com/App2Sales/react-native-switch-selector/releases/tag/1.1.4)

**Comment by luisbajana** [comment]
It works amazing! Thank you @jkdrangel

**Comment by Nitzperetz** [comment]
I am on using version `1.1.12` and swipe doesn't work for me. Am I missing anything?

**Comment by davStar** [comment]
Hello guys Which component you recommend for swiping with switch selector component? Thank you very much it is very urgent !!!

**Comment by davStar** [comment]
Hello, which swipe gesture lib you are using ?  I m blocked and don’t know how to implement it. Than k you very much in advance!!!

**Comment by davStar** [comment]
> It works perfect! Thank you @jkdrangel

Hello @jkdrangel ,

You mentioned it works for you with swipe gesture. May you help me please to know which module you are using and how you implement it. I m quite new in react native. Thank you,

**Comment by jkdrangel** [comment]
@davStar This lib use [PanResponder](https://reactnative.dev/docs/panresponder) API from de core of React Native
