### ISSUE TITLE
Invalid prop type `options`

### ISSUE THREAD

**Issue by jeniffer9** [App2Sales/react-native-switch-selector#64]
<img width="359" alt="Screen Shot 2020-05-28 at 10 56 28 AM" src="https://user-images.githubusercontent.com/24354470/83120870-e4798680-a0d1-11ea-85bf-285f92c4e82c.png">

Shouldn't the option prop require an array?

**Comment by ishaansehgal99** [comment]
I have this same issue.

**Comment by allandiego** [comment]
#63 already open to fix this

**Comment by jeniffer9** [comment]
Can the new version please be published on npm as well? :)
