### ISSUE TITLE
Problems with textColor and selectedColor

### ISSUE THREAD

**Issue by PauloFilipini** [App2Sales/react-native-switch-selector#65]
I've styled the text using the attribute textColor="#949494" and selectedColor="#FFF" but only textColor is being displayed with the correct color, It seems that selectedColor="#FFF" is being ignored. Could you help me?

**Comment by LeandroBernardo** [comment]
i've the trouble.

**Comment by ssscassio** [comment]
`selectedColor` is already '#FFFFFF' by default. What changes do you expect to see?

Maybe an image would help.
