### ISSUE TITLE
Change value according to state

### ISSUE THREAD

**Issue by lucaingold** [App2Sales/react-native-switch-selector#7]
Hi
I did not found a possibility, that the current selected value, can be change without pressing it manually on the screen. Could it be, that there is no way, to change the value according to the current state? I found the state 'selected' and a toogle-fuction in the library-code, but there is no way, to acces this code from outside. Do I miss something? Thank you!
Something like: 
```
<SwitchSelector
    options={options}
    initial={this.state.value}
    value={this.state.value}
    onPress={value => this.toggleButton(value)}
/>
```

**Comment by jkdrangel** [comment]
In the commit [1.1.5](https://github.com/App2Sales/react-native-switch-selector/commit/1c1e564ea4680045e24f5bd44245dbb131afbce4) I add a toogleItem call when the value prop changes. This resolve your problem?

**Comment by lucaingold** [comment]
Brilliant 👍 Thank you, that was exactly, what i searched for!
