### ISSUE TITLE
Switch selector not changing its values in "options" attribute when translated. 

### ISSUE THREAD

**Issue by YashMaurya9274** [App2Sales/react-native-switch-selector#79]
I have come across a problem ---> I'm using translations in my project and by default the language selected is English but whenever I change my translations to Hindi or any other language the "Yes or No" options in my Switch Selector does not change.

PS - the values in the switch selector for attribute "options" is defined in some other .js file and are being accessed from there
eg. translation.js --> LOGIN_WITH_SAME_EMAIL_ID =  [
  { label: "yes", value: strings.yes },
  { label: "no", value: strings.no },
]; 

// strings.js is another file containing translations of yes and no in different languages.

and 

<SwitchSelector
  initial={0}
  onPress={(value) => {//some function}}
  options={GLOBALS.LOGIN_WITH_SAME_EMAIL_ID}
/>

here the value is only converted when I go to translation.js and do a force save on the file..!
but when I use the direct way i.e. directly initializing "options" it works...
but I need to use the previous way, because all the translations should be accessed from an external .js file only.!

**Comment by ssscassio** [comment]
`label` property inside of the options object means the presented(visual) value of the switch, while the `value` property is the value that will be passed to the `SwitchSelector` `onPress` property when the switch values changes.
If I correcly understand your problem and implementation, I suggest you to change your translation.js this way:

```diff
LOGIN_WITH_SAME_EMAIL_ID = [
- { label: "yes", value: strings.yes },
- { label: "no", value: strings.no },
+ { label: strings.yes, value: "yes" },
+ { label: strings.no, value: "no" },
];
```
